CREATE OR REPLACE VIEW stareau_ass.ass_desserte
AS SELECT ac.type_reseau,
    ac.fictif,
    ac.etat_service,
    ac.insee_commune,
    ac.localisation,
    ac.maitre_ouvrage,
    ac.exploitant,
    ac.entreprise_pose,
    ac.precision_xy,
    ac.precision_z,
    ac.an_pose_sup,
    ac.an_pose_inf,
    ac.an_service_sup,
    ac.an_service_inf,
    ac.an_abandon_sup,
    ac.an_abandon_inf,
    ac.an_rehab_sup,
    ac.an_rehab_inf,
    ac.date_creation,
    ac.origine_creation,
    ac.date_maj,
    ac.origine_maj,
    ac.lien_doc1,
    ac.lien_doc2,
    ac.commentaire,
    ac.id_canalisation,
    ac.geom,
    ac.mode_circulation,
    ac.type_pose,
    ac.raison_pose,
    ac.materiau,
    ac.revetement_interieur,
    ac.diametre_equivalent,
    ac.longueur_terrain,
    ac.noeudterminal,
    ac.noeudinitial,
    ac.forme,
    ac.hauteur_interieure,
    ac.hauteur_exterieure,
    ac.largeur_interieure,
    ac.largeur_exterieure,
    ac.longueur_interieure,
    ac.longueur_exterieure,
    ac.id_ass_canalisation,
    ac.fonction_ass_canalisation,
    ac.visitable,
    ac.altitude_fil_eau_amont,
    ac.altitude_fil_eau_aval,
    ac.bassin_collecte,
    ac.ref_ouvrage_aval
   FROM stareau_ass.ass_canalisation ac
  WHERE ac.etat_service = 'en_service'::text AND ac.fictif = false;

  COMMENT ON VIEW stareau_ass.ass_desserte IS 'vue des canalisations ASS en service et non fictive';