-- stareau_aep.aep_desserte source

CREATE OR REPLACE VIEW stareau_aep.aep_desserte
AS SELECT
    ac.id_canalisation,
    ac.type_reseau,
    ac.fictif,
    ac.etat_service,
    ac.insee_commune,
    ac.localisation,
    ac.maitre_ouvrage,
    ac.exploitant,
    ac.entreprise_pose,
    ac.precision_xy,
    ac.precision_z,
    ac.an_pose_sup,
    ac.an_pose_inf,
    ac.an_service_sup,
    ac.an_service_inf,
    ac.an_abandon_sup,
    ac.an_abandon_inf,
    ac.an_rehab_sup,
    ac.an_rehab_inf,
    ac.date_creation,
    ac.origine_creation,
    ac.date_maj,
    ac.origine_maj,
    ac.lien_doc1,
    ac.lien_doc2,
    ac.commentaire,
    ac.mode_circulation,
    ac.type_pose,
    ac.raison_pose,
    ac.materiau,
    ac.revetement_interieur,
    ac.diametre_equivalent,
    ac.longueur_terrain,
    ac.noeudterminal,
    ac.noeudinitial,
    ac.forme,
    ac.hauteur_interieure,
    ac.hauteur_exterieure,
    ac.largeur_interieure,
    ac.largeur_exterieure,
    ac.longueur_interieure,
    ac.longueur_exterieure,
    ac.id_aep_canalisation,
    ac.fonction_canalisation,
    ac.contenu_canalisation,
    ac.protection_cathodique,
    ac.etage_pression,
    ac.type_pression,
    ac.secteur_hydraulique,
    ac.ref_udi,
    ac.cote_debut,
    ac.cote_fin,
    ac.geom
   FROM stareau_aep.aep_canalisation ac
  WHERE ac.etat_service = 'en_service'::text AND ac.fictif = false;

COMMENT ON VIEW stareau_aep.aep_desserte IS 'vue des canalisations AEP en service et non fictive';